import { Router } from 'express';
import { adminRouter } from './admin.js';
import { authRouter } from './auth.js';
import { dashboardRouter } from './dashboard.js';
import { healthRouter } from './health.js';
import { landingRouter } from './landing.js';
import { lookingForTeamRouter } from './looking-for-team.js';
import { matchesRouter } from './matches.js';
import { notificationsRouter } from './notifications.js';
import { profileRouter } from './profile.js';
import { sportsRouter } from './sports.js';
import { recruitmentRouter } from './recruitment.js';
import { reportsRouter } from './reports.js';
import { teamsRouter } from './teams.js';
import { venuesRouter } from './venues.js';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/profile', profileRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/teams', teamsRouter);
apiRouter.use('/recruitment', recruitmentRouter);
apiRouter.use('/looking-for-team', lookingForTeamRouter);
apiRouter.use('/landing', landingRouter);
apiRouter.use('/sports', sportsRouter);
apiRouter.use('/matches', matchesRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/venues', venuesRouter);
apiRouter.use('/admin', adminRouter);
